version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - yum update -y
      - wget https://extras.getpagespeed.com/redhat/8/x86_64/RPMS/google-chrome-stable_current_x86_64.rpm
      - yum install google-chrome*.rpm -y
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: 'dist/angular-unit-testing'
