version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install enhanced-resolve@4.1.1
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run package
artifacts:
  files:
    - "**/*"
  base-directory: dist
