version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - yum update -y
      - yum install -y dpkg fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://extras.getpagespeed.com/redhat/8/x86_64/RPMS/google-chrome-stable_current_x86_64.rpm
      - yum install google-chrome*.rpm -y
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
  post_build:
    commands:
      - aws s3 sync ./ s3://devops-project-bucket/codebuild-artifacts --acl 'public-read' --delete
artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: '/'
