version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install -g jasmine
      - npm install gulp-jasmine-browser
  build:
    commands:
      - npm run test
  post_build:
    commands:
      - npm run package
artifacts:
  files:
    - "**/*"
  base-directory: dist
