version: 0.2

env:
  variables:
    CHROME_BIN: /usr/bin/google-chrome karma start --single-run

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm install puppeteer
      - npm install -g jasmine
  build:
    commands:
      - npm run test-headless
  post_build:
    commands:
      - npm run package
artifacts:
  files:
    - "**/*"
  base-directory: dist
